# Generated by Django 4.0.6 on 2022-07-28 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_alter_customer_password_alter_customer_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='image',
            field=models.ImageField(default=0, upload_to='myproject/media'),
        ),
        migrations.AddField(
            model_name='customer',
            name='pub_date',
            field=models.DateField(null=True),
        ),
    ]
