# Generated by Django 4.0.6 on 2022-07-28 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_customer_image_customer_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='image',
            field=models.ImageField(default=0, upload_to='myproject/media/'),
        ),
    ]
