# Generated by Django 4.0.6 on 2022-07-28 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_alter_customer_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='image',
            field=models.ImageField(default=0, upload_to='images/'),
        ),
    ]
