# Generated by Django 4.0.6 on 2022-08-02 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0011_alter_customer_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='customer_id',
            field=models.IntegerField(default=True),
        ),
    ]
